import { writable } from "svelte/store";

export const editor = writable();
export const templatesModal = writable(false);
export const publishModal = writable(false);
export const previewModal = writable(false);
export const currentTemplate = writable({ id: null, name: null });
export const preview = writable();
export const templates = writable([]);
export const selectedObj = writable();
export const items = writable([]);
export const history = writable([]);
export const historyMods = writable(0);
export const colorWidget = writable(false);
export const skewWidget = writable(false);
export const resizeWidget = writable(false);
export const textWidget = writable(false);
export const freeDrawingMode = writable(false);
export const colorValue = writable("#000");
export const fillStroke = writable();
export const canvasBg = writable();
export const unfinishedModal = writable(false);
export const filterWidget = writable(false);
export const shadowColor = writable("#000");
